In [0]:
import numpy as np

array =np.random.randint(1,10,size=4).reshape(2,2)
print(array)

[[2 8]
 [6 1]]


In [0]:
result_array = array * 2
result_array

array([[ 4, 16],
       [12,  2]])

In [0]:
import numpy as np
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)

array3 = array1 + array2

array3

array([[0, 2],
       [2, 4]])

In [0]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis = 0)
array4 = np.arange(0, 4).reshape(4 ,1) #(4 x 1)

print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [0]:
#Numpy의 마스킹 연산
#각 원소에 대해 T/F 값 부여
import numpy as np

array1 = np.arange(16).reshape(4,4)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [0]:
import numpy as np

array = np.arange(16).reshape(4,4)

# np.max , min , sum , min
print(array)
print("합계: " , np.sum(array,axis=0)) #열 합치기

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]


In [1]:


import tensorflow as tf

# Set up a linear classifier.
classifier = tf.estimator.LinearClassifier()

# Train the model on some example data.
classifier.train(input_fn=train_input_fn, steps=2000)

# Use it to predict.
predictions = classifier.predict(input_fn=predict_input_fn)

TypeError: ignored